default: &default
  adapter: postgresql
  timeout: 5000
  username: <%= ENV.fetch("DB_USER", "femboyfans") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "postgres") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: reports_development
  pool: 5

test:
  <<: *default
  database: reports_test
  pool: 5

<% if Rails.env.production? %>
production:
  <<: *default
  database: reports
  pool: <%= ENV.fetch("DB_POOL_SIZE", 5) %>
<% end %>
