name: Docker Build

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'pawsmovin'

    steps:
      - name: Publish to ghcr
        uses: e621ng/publish-to-ghcr@v1
